### ISSUE TITLE
billingAddress Issue 

### ISSUE THREAD

**Issue by amolkarma** [eStream/Cart42#7]
billingAddress I Cannot be Add into Addressess

**Comment by estoev** [comment]
What are the steps to reproduce the issue?

**Comment by amolkarma** [comment]
Issue in following line  user.Addresses.Add(billingAddress); billingAddress cannot be Add into Addressess. how to fix this Issue.

**Comment by estoev** [comment]
Please provide the exact steps so that I can reproduce the issue

**Comment by amolkarma** [comment]
Issue in Following Line
 billingAddress = Mapper.Map<Address>(model.BillingAddress);

**Comment by amolkarma** [comment]
Shipping Method Cannot be Display in  Checkout

**Comment by estoev** [comment]
Could you provide the error message or stack trace of the error?

**Comment by amolkarma** [comment]
i am give the shippingmethod id hardcoded that time work properly but without hardcoded id  shipping method cannot be Display
